export const themes = {
  "3024-night": "3024 Night",
  "blackboard": "Blackboard",
  "base16-dark": "Base 16 (Dark)",
  "base16-light": "Base 16 (Light)",
  "cobalt": "Cobalt",
  "dracula": "Dracula",
  "duotone-dark": "Duotone",
  "hopscotch": "Hopscotch",
  "lucario": "Lucario",
  "material": "Material",
  "monokai": "Monokai",
  "night-owl": "Night Owl",
  "nord": "Nord",
  "oceanic-next": "Oceanic Next",
  "one-dark": "One Dark",
  "panda-syntax": "Panda",
  "paraiso-dark": "Paraiso",
  "seti": "Seti",
  "solarized dark": "Solarized (Dark)",
  "solarized light": "Solarized (Light)",
  "tomorrow-night-bright": "Tomorrow Night",
  "twilight": "Twilight",
  "verminal": "Verminal",
  "yeti": "Yeti",
  "zenburn": "Zenburn"
}
